pub mod hooks;
pub mod inspector_view;
pub mod state;
pub mod tree;

// Re-export the macros
pub use gpui_inspector_macros::{auto_inspector, inspector, inspector_main};

/// The function called by the code generated by the inspector macro.
pub fn set_rendered_tree(node: tree::RenderedNode) {
    *state::RENDER_TREE.lock() = Some(node);
}

pub fn print_rendered_node_to_console(node: &tree::RenderedNode) {
    println!("Render {}:", node.component_name);
    if let Some(element_tree) = &node.element_tree {
        print_element_node(element_tree, 0);
    }
}

fn print_element_node(node: &tree::ElementNode, indent_level: usize) {
    let indent = "  ".repeat(indent_level);
    println!("{}{}(id: {})", indent, node.name, node.id);
    for (prop, value) in &node.properties {
        println!("{}.{}(\"{}\")", indent, prop, value);
    }
    for child in &node.children {
        print_element_node(child, indent_level + 1);
    }
}
