// GPUI Inspector: Runtime inspection tool for GPUI applications
//
// This library provides tools to inspect and visualize the UI element tree
// of running GPUI applications for debugging and development purposes.

// Core modules
pub mod core;
pub mod hooks;
pub mod ui;
pub mod utils;

// Re-export commonly used items for convenience
pub use core::{ElementNode, RenderedNode};
pub use ui::InspectorView;

// Re-export modules for backward compatibility
pub use ui::views::inspector_view;
pub mod tree {
    pub use crate::core::tree::*;
}

// Re-export the macros from gpui-inspector-macros
pub use gpui_inspector_macros::{auto_inspector, inspector, inspector_main};

// Re-export core state functions
pub use core::{set_tree_update_callback, ALL_TREES, RENDER_TREE};

/// The function called by the code generated by the inspector macro.
///
/// This saves the rendered tree to both the main RENDER_TREE (for the currently
/// inspected view) and the ALL_TREES map (for entity expansion).
pub fn set_rendered_tree(node: RenderedNode) {
    // Save to the main tree (for the target view)
    *core::RENDER_TREE.lock() = Some(node.clone());

    // Also save to the all_trees map by component name
    core::ALL_TREES
        .lock()
        .insert(node.component_name.clone(), node);

    core::increment_tree_version();
}

/// Expand Entity references in a tree by substituting them with their actual rendered content.
///
/// This function recursively traverses the tree and replaces Entity<View> nodes
/// with the actual rendered content of those views.
pub fn expand_entities_in_tree(node: &mut ElementNode) {
    use std::collections::HashSet;
    let mut visited = HashSet::new();
    expand_entities_in_tree_impl(node, &mut visited);
}

fn expand_entities_in_tree_impl(
    node: &mut ElementNode,
    visited: &mut std::collections::HashSet<String>,
) {
    // Check if this node is an Entity reference (e.g., "self.tab1_view")
    if node.name.contains("_view") && node.name.contains("self.") {
        // Extract the view name (e.g., "tab1_view" from "self.tab1_view")
        let view_name = node.name.replace("self.", "").replace(" .clone()", "");

        // Try to find a matching tree by checking if any component name contains this view name
        // For Tab1, we look for a tree named "Tab1"
        let component_name = if view_name.starts_with("tab") {
            // Convert "tab1_view" -> "Tab1"
            let num = view_name.chars().nth(3).unwrap_or('1');
            format!("Tab{}", num)
        } else {
            view_name.clone()
        };

        // Prevent infinite recursion by checking if we've already visited this component
        if visited.contains(&component_name) {
            return;
        }
        visited.insert(component_name.clone());

        // Clone the needed data while holding the lock, then release it immediately
        let element_tree_clone = {
            let all_trees = core::ALL_TREES.lock();
            all_trees
                .get(&component_name)
                .and_then(|rendered_node| rendered_node.element_tree.clone())
        }; // Lock is released here

        if let Some(element_tree) = element_tree_clone {
            // Replace this node with the actual content
            *node = element_tree;
            // Continue expanding the children of the newly substituted node
            // This ensures we expand any nested Entity references as well
            for child in &mut node.children {
                expand_entities_in_tree_impl(child, visited);
            }
            return;
        }
    }

    // Recursively expand children (lock is not held here)
    for child in &mut node.children {
        expand_entities_in_tree_impl(child, visited);
    }
}

/// Print a rendered node to the console for debugging.
pub fn print_rendered_node_to_console(node: &RenderedNode) {
    println!("Render {}:", node.component_name);
    if let Some(element_tree) = &node.element_tree {
        print_element_node(element_tree, 0);
    }
}

fn print_element_node(node: &ElementNode, indent_level: usize) {
    let indent = "  ".repeat(indent_level);

    // Print the node name
    print!("{}{}", indent, node.name);

    // Print properties inline (compact format)
    let mut important_props = Vec::new();
    for (prop, value) in &node.properties {
        // Truncate very long values (like closures)
        let truncated_value = if value.len() > 50 {
            format!("{}...", &value[..47])
        } else {
            value.clone()
        };
        important_props.push(format!(".{}({})", prop, truncated_value));
    }

    if !important_props.is_empty() {
        println!(" {}", important_props.join(" "));
    } else {
        println!();
    }

    // Print children recursively
    for child in &node.children {
        print_element_node(child, indent_level + 1);
    }
}
