pub mod hooks;
pub mod inspector_view;
pub mod state;
pub mod tree;

// Re-export the macros
pub use gpui_inspector_macros::{auto_inspector, inspector, inspector_main};

pub fn builder_start() {
    state::TREE_BUILDER.with(|b| b.borrow_mut().start());
}

pub fn builder_enter(name: &str) {
    state::TREE_BUILDER.with(|b| b.borrow_mut().enter_node(name));
}

pub fn builder_exit() {
    state::TREE_BUILDER.with(|b| b.borrow_mut().exit_node());
}

pub fn builder_prop(name: &str, value: String) {
    state::TREE_BUILDER.with(|b| b.borrow_mut().add_property(name, value));
}

pub fn builder_id(id: String) {
    state::TREE_BUILDER.with(|b| b.borrow_mut().set_global_id(id));
}

pub fn builder_path(path: String) {
    state::TREE_BUILDER.with(|b| b.borrow_mut().set_global_path(path));
}

pub fn builder_finish(component_name: &str) {
    let tree_option = state::TREE_BUILDER.with(|b| b.borrow_mut().root.take());
    if let Some(tree) = tree_option {
        let node = tree::RenderedNode {
            version: 0,
            component_name: component_name.to_string(),
            element_tree: Some(tree),
            gpui_element_ids: std::collections::HashMap::new(),
        };
        set_rendered_tree(node);
    }
}

/// The function called by the code generated by the inspector macro.
pub fn set_rendered_tree(mut node: tree::RenderedNode) {
    let mut tree = state::RENDER_TREE.lock();
    let current_version = tree.as_ref().map(|t| t.version).unwrap_or(0);
    node.version = current_version + 1;
    // println!("[Inspector] Tree updated: {} (v{})", node.component_name, node.version);
    *tree = Some(std::sync::Arc::new(node));
}

pub fn print_rendered_node_to_console(node: &tree::RenderedNode) {
    println!("Render {}:", node.component_name);
    if let Some(element_tree) = &node.element_tree {
        print_element_node(element_tree, 0);
    }
}

fn print_element_node(node: &tree::ElementNode, indent_level: usize) {
    let indent = "  ".repeat(indent_level);
    println!("{}{}(id: {})", indent, node.name, node.id);
    for (prop, value) in &node.properties {
        println!("{}.{}(\"{}\")", indent, prop, value);
    }
    for child in &node.children {
        print_element_node(child, indent_level + 1);
    }
}
